name: Check hugo build

'on':
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
        ssh-key: ''

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2

    - name: Build
      run: hugo --minify
